services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports: ["8081:8080"]
    depends_on: [db]
    env_file: .env

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-sejawat_new}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-qwery}
      MYSQL_PASSWORD: ${DB_PASSWORD:-qwery}
      MYSQL_USER: ${DB_USERNAME:-root}
    ports: ["3306:3306"]
    volumes: [dbdata:/var/lib/mysql]

volumes:
  dbdata:
