services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports: ["8081:80"]
    volumes:
      - .:/var/www
    depends_on: [db]
    env_file: .env

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-sejawat_new}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-qwerty}
      MYSQL_PASSWORD: ${DB_PASSWORD:-qwerty}
      MYSQL_USER: ${DB_USERNAME:-root}
    ports: ["3306:3306"]
    volumes: [dbdata:/var/lib/mysql]

  composer:
    image: composer:2
    working_dir: /app
    volumes: [.:/app]
    entrypoint: ["sh","-lc","composer install && composer dump-autoload -o"]

  node:
    image: node:lts-alpine
    working_dir: /var/www/html
    volumes: [.:/var/www/html]
    ports: ["5173:5173"]
    command: npm run dev

volumes:
  dbdata:
